"""add_validation_breakdown

Revision ID: 1dcf70ed71ee
Revises: fd1aa105ec38
Create Date: 2026-06-17 16:31:32.793232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcf70ed71ee'
down_revision: Union[str, Sequence[str], None] = 'fd1aa105ec38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('validation_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'validation_breakdown')
    # ### end Alembic commands ###
