"""initial_schema

Revision ID: fd1aa105ec38
Revises: 
Create Date: 2026-06-17 13:16:17.806471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd1aa105ec38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('phone_regex', sa.String(length=255), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_rules_country_code'), 'country_rules', ['country_code'], unique=False)
    op.create_index('uq_country_rules_active_code', 'country_rules', ['country_code'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=50), nullable=False, comment='Unique tracking identifier e.g. TXN-12345'),
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued | processing | completed | failed'),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('valid_records', sa.Integer(), nullable=True),
    sa.Column('invalid_records', sa.Integer(), nullable=True),
    sa.Column('clean_file_path', sa.String(length=512), nullable=True),
    sa.Column('error_report_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_uploaded_file_id'), 'processing_jobs', ['uploaded_file_id'], unique=False)
    op.create_table('ai_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('common_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('country_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reports_job_id'), 'ai_reports', ['job_id'], unique=True)
    op.create_table('validation_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False, comment='missing_field | negative_value | invalid_phone | ...'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_logs_error_type'), 'validation_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_validation_logs_job_id'), 'validation_logs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_logs_job_id'), table_name='validation_logs')
    op.drop_index(op.f('ix_validation_logs_error_type'), table_name='validation_logs')
    op.drop_table('validation_logs')
    op.drop_index(op.f('ix_ai_reports_job_id'), table_name='ai_reports')
    op.drop_table('ai_reports')
    op.drop_index(op.f('ix_processing_jobs_uploaded_file_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_table('uploaded_files')
    op.drop_index('uq_country_rules_active_code', table_name='country_rules', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index(op.f('ix_country_rules_country_code'), table_name='country_rules')
    op.drop_table('country_rules')
    # ### end Alembic commands ###
